[package]
name = "lexicon"
version = "0.1.0"
edition = "2021"
description = "A trie-based library used by lexiterm for searching words."

[dependencies]
regex = "1.11.1"
serde_json = "1.0.140"
thiserror = "2.0.12"

[dev-dependencies]
pretty_assertions = "1.4.1"
