name: Security audit
on:
  # every midnight, UTC
  schedule:
    - cron: '0 0 * * *'

  # every time a Cargo.toml or Cargo.lock is updated
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories --config .cargo-deny.toml
